@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "pokemon.Pokemon",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_399033133 { 
   	label=pokemon
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Attaque399033133[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Attaque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categorie: AttaqueCategorie [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   puissance: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   type: Type [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Pokemon399033133[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Pokemon</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   attaque: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   attaque_speciale: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   attaques_apprises: Attaque[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   defence: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   defence_speciale: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   possibles_attaques: ArrayList&lt;Attaque&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pv: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   types: ArrayList&lt;Type&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vitesse: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addPossibles_attaques(attaque: Attaque)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addTypes(type: Type)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Type399033133[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Type</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   faiblesses: ArrayList&lt;Type&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   resistances: ArrayList&lt;Type&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addFaiblesse(t: Type)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addResistance(t: Type)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Attaque399033133 -> Type399033133[label="type
[0..1]"];
Pokemon399033133 -> Attaque399033133[label="attaques_apprises
[0..*]"];
Pokemon399033133 -> Attaque399033133[label="possibles_attaques
[0..*]"];
Pokemon399033133 -> Type399033133[label="types
[0..*]"];
    
}
@enduml